# Generated by Django 4.1.5 on 2023-01-19 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=4, max_digits=4)),
                ('document', models.FileField(upload_to='')),
                ('interviewTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
