# Generated by Django 4.0 on 2023-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='skillSet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
