# Generated by Django 4.1.5 on 2023-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='score',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
    ]
