# Generated by Django 4.1.5 on 2023-02-02 09:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_jobdetails_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='skillSet',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=666, null=True, size=6),
        ),
    ]
