# Generated by Django 4.1.5 on 2023-02-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_jobdetails_interviewday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
