# Generated by Django 4.1.5 on 2023-02-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_jobdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
