# Generated by Django 4.1.5 on 2023-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_remove_jobdetails_interviewtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
