# Generated by Django 4.1.5 on 2023-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_jobdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
